export const termsContent = {
effectiveDate: 'September 13, 2025',
sections: [
{
title: '1. Introduction & Acceptance of Terms',
content: `Welcome to ImmiGo ("we", "our", "us"). These Terms and Conditions ("Terms") govern your use of our web application and services (collectively, the "Service"). By creating an account or using our Service, you agree to be bound by these Terms in full. If you do not agree with any part of the terms, then you do not have permission to access the Service.`,
    },
    {
      title: '2. The Service',
      content: `ImmiGo provides an artificial intelligence-powered conversational partner designed to assist users. The responses generated by the AI are for informational and entertainment purposes only and should not be considered as professional, legal, financial, or medical advice.`,
    },
    {
      title: '3. User Accounts',
      content: `To access the Service, you must create an account. You are responsible for safeguarding your account password and for any activities or actions under your account. You agree to provide accurate and complete information and to keep this information up to date.`,
    },
    {
      title: '4. User-Generated Content',
      content: `The conversations you have with the AI, including any text you input ("User Content"), are processed by our Service. By using the Service, you grant us a worldwide, non-exclusive, royalty-free license to use, process, and store your User Content for the purposes of providing and improving the Service. You retain all ownership rights to your original User Content.`,
    },
    {
      title: '5. Acceptable Use Policy',
      content: `You agree not to use the Service for any unlawful purpose or to engage in any activity that is harmful, threatening, abusive, or harassing. You may not use the Service to generate content that infringes on any third-party rights, including intellectual property rights. We reserve the right to terminate accounts that violate this policy.`,
    },
    {
      title: '6. Intellectual Property',
      content: `The Service and its original content (excluding User Content), features, and functionality are and will remain the exclusive property of ImmiGo and its licensors. Our trademarks and trade dress may not be used in connection with any product or service without our prior written consent.`,
    },
    {
      title: '7. Disclaimers and Limitation of Liability',
      content: `THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. WE MAKE NO WARRANTIES, EXPRESS OR IMPLIED, REGARDING THE ACCURACY, RELIABILITY, OR COMPLETENESS OF THE AI-GENERATED RESPONSES. IN NO EVENT SHALL IMMIGO, NOR ITS DIRECTORS, EMPLOYEES, OR PARTNERS, BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, OR OTHER INTANGIBLES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE.`,
    },
    {
      title: '8. Governing Law',
      content: `These Terms shall be governed and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions.`,
    },
    {
      title: '9. Changes to Terms',
      content: `We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.`,
    },
    {
      title: '10. Contact Us',
      content: `If you have any questions about these Terms, please contact us at legal@immigo.ai.`,
    },
  ],
};